const EC_SUCCESS = 0;
const EC_USER_TERMINATED = 1;
const EC_HELP_DISPLAYED = 2;
const EC_VERSION_DISPLAYED = 3;

module.exports = {
  EC_SUCCESS,
  EC_USER_TERMINATED,
  EC_HELP_DISPLAYED,
  EC_VERSION_DISPLAYED,
};
